### ISSUE TITLE
Error with MapTnSeq 

### ISSUE THREAD

**Issue by hmamine** [m-jahn/TnSeq-pipe#12]
I am encountering an error that I am not sure how to fix. Below the output I got; 
```
someone@somemachine:~/Biotools/TnSeq-pipe$ source/run_tnseq_mapping.sh --ref ASM9156v1
Output directory: data/mapped/ exists
Output directory: data/pool/ exists
Error in library(tidyverse) : there is no package called ‘tidyverse’
Calls: suppressPackageStartupMessages -> withCallingHandlers -> library
Execution halted
Input file pattern matches: .*.fastq.gz$
Input files matching pattern: 6
Parsed model feba/primers/model_pKMW7
Barcodes of length 20, expected transposon region of 105
Reads (gzipped) from data/fastq//Ea_ML1_R1_001.fastq.gz
Read 41859882 reads
Error reading 4096 bytes: Operation not permitted
Cannot run blat: Inappropriate ioctl for device at feba/bin/MapTnSeq.pl line 399.
```
I have installed blat as recommended `[here](https://bioinformaticsreview.com/20200822/installing-blat-a-pairwise-alignment-tool-on-ubuntu/)` and I am not sure whether this is the issue or something else. I would appreciate any helps, Thanks.

**Comment by m-jahn** [comment]
Dear Amine,
Your error log suggests several problems. First of all, you should make sure that your R installation has the `tidyverse` meta package installed. This is the error in line 4. However that might not might not be the reason why the script terminates, because you also got an error with blat.
What I did (and I think it's also written in the TnSeq README) is simply to download the `blat` executable (follow link in README) and move it to the `./feba/bin/` dir. The scripts will find the blat executable automatically, no need to set an environment flag, do make / configure or anything like that. Don't compile from source, just use the executable as it is.

**Comment by m-jahn** [comment]
If you are using linux, this is the right download page for blat: https://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/blat/

**Comment by LZC0034** [comment]
Hi,  I was trying to run "source/run_tnseq_mapping.sh --pattern H16.* --ref ASM928v2" on the example in the github. However, I kept receiving the errors attached below. For the blat, I did wget it from "https://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/blat/." I appreciate any suggestions to solve this issue.  

<details><summary>Details</summary>
<p>

"Searching NCBI for supplied assembly ID: ASM928v2
Error in curl::curl_fetch_memory(url, handle = handle) :
  Could not resolve host: eutils.ncbi.nlm.nih.gov
Calls: entrez_search ... request_fetch -> request_fetch.write_memory -> <Anonymous>
Execution halted
Parsed model feba/primers/model_pKMW7
Barcodes of length 20, expected transposon region of 105
Reads (gzipped) from data/fastq//H16_S2_L001_R1_001.fastq.gz
Read 419276 reads
can only read regular files with readInGulp: ref//
Cannot run /scratch/network/cl9312/data/TnSeq-Azenta/TnSeq-pipe/feba/bin/blat: Inappropriate ioctl for device at feba/bin/MapTnSeq.pl line 399.
Parsed model feba/primers/model_pKMW7
Barcodes of length 20, expected transposon region of 105
Reads (gzipped) from data/fastq//H16_S2_L001_R2_001.fastq.gz
Read 0 reads
None of the reads are candidates for mapping (none match the model and are long enough)
^M#   0 sec                                                                       ^M0^MESC[7mESC[0m0% 0:0=0s                                                                       ESC[0m
Reading mapping files:
data/mapped/H16_S2_L001_R1_001.tsv
data/mapped/H16_S2_L001_R2_001.tsv
Read 0 mapped reads for 0 distinct barcodes
0 barcodes seen 1 or more times, map 0 (minFrac 0.75 minRatio 8)
Masked 0 off-by-1 barcodes (0 reads) leaving 0 barcodes
Reads for those barcodes: 0 of 0 (0.0%)
Chao2 estimate of #barcodes present (may be inflated for sequencing error): 0"

</p>
</details>

**Comment by m-jahn** [comment]
This is difficult to reproduce for me. But it seems the mapping with `blat` does still not work:

```
Cannot run /scratch/network/cl9312/data/TnSeq-Azenta/TnSeq-pipe/feba/bin/blat: Inappropriate ioctl for device at feba/bin/MapTnSeq.pl line 399.
```

Have you set the executable bit on the `blat` executable? Does your user have permission to run the executable and access all necessary files and dirs?
You can check with `ls -l` in your /feba/bin dir. For me permissions look like this:

```
-rwxrwxr-x 1 michael michael   18293 Sep 15  2022 BarSeqR.pl
-rwxrwxr-x 1 michael michael    5040 Sep 15  2022 BarSeqTest.pl
-rwxrwxr-x 1 michael michael    9270 Sep 15  2022 batch_setup_tables.pl
-rwxrwxr-x 1 michael michael    5459 Sep 15  2022 bbh.pl
-rwxrw-r-- 1 michael michael 6621744 Sep 28  2022 blat
```

Note that I as a user have `rwx` permission for blat.

**Comment by LZC0034** [comment]
#

> This is difficult to reproduce for me. But it seems the mapping with `blat` does still not work:
> 
> ```
> Cannot run /scratch/network/cl9312/data/TnSeq-Azenta/TnSeq-pipe/feba/bin/blat: Inappropriate ioctl for device at feba/bin/MapTnSeq.pl line 399.
> ```
> 
> Have you set the executable bit on the `blat` executable? Does your user have permission to run the executable and access all necessary files and dirs? You can check with `ls -l` in your /feba/bin dir. For me permissions look like this:
> 
> ```
> -rwxrwxr-x 1 michael michael   18293 Sep 15  2022 BarSeqR.pl
> -rwxrwxr-x 1 michael michael    5040 Sep 15  2022 BarSeqTest.pl
> -rwxrwxr-x 1 michael michael    9270 Sep 15  2022 batch_setup_tables.pl
> -rwxrwxr-x 1 michael michael    5459 Sep 15  2022 bbh.pl
> -rwxrw-r-- 1 michael michael 6621744 Sep 28  2022 blat
> ```
> 
> Note that I as a user have `rwx` permission for blat.

Thanks for your advice. I have set 'rwx' permission on blat. I realized blat cannot be run because the assembly reference files (<assembly>.gff, <assembly>.gbk, <assembly>.fna) could not be fetched from the NCBI host. Do you have any suggestions for this? I appreciate it. 

> Searching NCBI for supplied assembly ID: ASM928v2
Error in curl::curl_fetch_memory(url, handle = handle) :
  Could not resolve host: eutils.ncbi.nlm.nih.gov
Calls: entrez_search ... request_fetch -> request_fetch.write_memory -> <Anonymous>
Execution halted
Parsed model feba/primers/model_pKMW7
Barcodes of length 20, expected transposon region of 105
Reads (gzipped) from data/fastq//H16_S2_L001_R1_001.fastq.gz
Read 419276 reads
can only read regular files with readInGulp: ref//
Cannot run /home/cl9312/projects/RB-TnSeq/TnSeq-pipe/TnSeq-pipe/feba/bin/blat: Inappropriate ioctl for device at feba/bin/MapTnSeq.pl line 399.

**Comment by hmamine** [comment]
> If you are using linux, this is the right download page for blat: https://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/blat/

Hello Michael, 
Thank you for your prompt reply, I have tried again after following your instructions. 
It is still getting similar error. I change permission to blat. I am not sure how to fix it. 
_`Cannot run /home/mahassani/Biotools/TnSeq-pipe/feba/bin/blat: Inappropriate ioctl for device at feba/bin/MapTnSeq.pl line 399`_
For information, got to check similar issues `[here](https://github.com/pyinvoke/invoke/issues/425)`, but I am not able to look in detail into the scripts. 
Currently, I am following the pipe step by step, perl feba/bin/MapTnSeq. pl is working

**Comment by hmamine** [comment]
I indicated the output of MapTnSeq. pl, in case it helps for debug.

```
$ perl feba/bin/MapTnSeq.pl -stepSize 7 -tileSize 7 -genome ref/GCA_000091565.1_ASM9156v1_genomic.fna -model feba/primers/model_pKMW7 -first data/fastq/Ea_ML1_R1_001.fastq.gz -unmapped data/mapped/unmapped.txt -trunc data/mapped/trunc.txt > data/mapped/Ea_ML1_R1.txt
Parsed model feba/primers/model_pKMW7
Barcodes of length 20, expected transposon region of 105
Reads (gzipped) from data/fastq/Ea_ML1_R1_001.fastq.gz
Read 41859882 reads
Wrote 2624 unmapped reads to data/mapped/unmapped.txt in fasta format
Reads processed 41859882 Long-enough 41859882 Barcodes found 27226775
Mapping attempted for 2685 Mapped 61 Uniquely 60
Hits past end of transposon: 0 plus 0 weak/ambiguous; trumped hit to genome 0 times
Proportions: Long-enough 1.000 Barcode 0.650 Attempted 0.000 Mapped 0.000 Past-end 0.000

```

**Comment by m-jahn** [comment]
From your results I assume that `blat` works now, as it is trying to map reads to a genome and you get reasonable output?
The number of reads where mapping was attempted is very low (~2,600 compared to 27M reads with barcode), have you an idea why?
Did you manage to download the genome annotation (fasta and gff files)?

If you solve some of the issues yourself, can you post the solution here? Maybe that helps with future problems, or I can fix some of the things directly.

**Comment by m-jahn** [comment]
I added the required R dependencies to the README (tidyverse, Rcurl + libcurl, etc). These were missing and causing some of the errors regarding fetching the library. I tested the pipeline just now and it worked for me with the test data.

**Comment by hmamine** [comment]
Thank you, I found the issue the prepare_ref_genome.R had not all required library, although I though I installed this but as using different env, it kind of mess up! The pipe continues although no genome is downloaded which give the weird error. 
As a small suggestion, it would help for debug if the pipe abort if none of the packages are installed or if *.fna and/or *.gff are not found ref ~ Thanks a lot for this useful pipeline. 
BTW, my data needs to be re-sequenced :(

**Comment by m-jahn** [comment]
Thanks for your feedback, much appreciated.
>As a small suggestion, it would help for debug if the pipe abort if none of the packages are installed or if *.fna and/or *.gff are not found ref ~ Thanks a lot for this useful pipeline.

Yes, good point, I try to include such checks for input files. In the end the pipeline wasn't really supposed to be useful for the public, but it seems to be now.

>BTW, my data needs to be re-sequenced :(

Sorry to hear, is that related to the problem with few reads mapping to the genome?
We had this problem too (not related to the pipeline). I recommend to look at the fastq files directly and map reads manually, just to investigate what the problem could be.

**Comment by LZC0034** [comment]
> 

Thanks for your suggestions. I followed the instruction and install all the required packages. I ran the script and there was no error in curl to resolve host this time, but I got another error message.  

> source/run_tnseq_mapping.sh --pattern H16.* --ref ASM928v2
Output directory: data/mapped/ exists
Output directory: data/pool/ exists
Searching NCBI for supplied assembly ID: ASM928v2
Error: Vector of IDs to send to NCBI is empty, perhaps entrez_search or entrez_link found no hits?
Execution halted

**Comment by m-jahn** [comment]
@LZC0034 
Have you checked your internet connection? Do you have a recent version of `rentrez`?
This problem should be easy to debug. If you just try the `rentrez` import in your R session you should be able to find the problem.
Try these commands taken from the script.

```
library(rentrez)
assembly = "ASM928v2"
search_result <- entrez_search(db = "assembly", term = assembly)
search_summary <- entrez_summary(db = "assembly", id = search_result$ids)
```

The `search_summary` object should be a longer list with annotation entries like this:

```
> search_summary$organism
[1] "Cupriavidus necator H16 (b-proteobacteria)"
> search_summary
esummary result with 54 items:
 [1] uid                         rsuid                      
 [3] gbuid                       assemblyaccession          
 [5] lastmajorreleaseaccession   latestaccession            
 [7] chainid                     assemblyname               
 [9] ucscname                    ensemblname                
[11] taxid                       organism                   
[13] speciestaxid                speciesname                
[15] assemblytype                assemblystatus             
[17] assemblystatussort          wgs                        
[19] gb_bioprojects              gb_projects                
[21] rs_bioprojects              rs_projects                
[23] biosampleaccn               biosampleid                
[25] biosource                   coverage                   
[27] partialgenomerepresentation primary                    
[29] assemblydescription         releaselevel               
[31] releasetype                 asmreleasedate_genbank     
[33] asmreleasedate_refseq       seqreleasedate             
[35] asmupdatedate               submissiondate             
[37] lastupdatedate              submitterorganization      
[39] refseq_category             anomalouslist              
[41] exclfromrefseq              propertylist               
[43] fromtype                    synonym                    
[45] contign50                   scaffoldn50                
[47] annotrpturl                 ftppath_genbank            
[49] ftppath_refseq              ftppath_assembly_rpt       
[51] ftppath_stats_rpt           ftppath_regions_rpt        
[53] busco                       sortorder  
```

**Comment by LZC0034** [comment]
@m-jahn 
Thanks for your instruction. I realized I added quotation marks on assembly after the "term =" previously. It is working now after I remove the marks. 

> search_result <- entrez_search(db = "assembly", term = "assembly")
