### ISSUE TITLE
Reference genome in TnSeq-pipe.Rmd is hardcoded

### ISSUE THREAD

**Issue by julienmortier** [m-jahn/TnSeq-pipe#5]
Reference genome in TnSeq-pipe.Rmd is hardcoded in line 49, which is inconvenient for using this with other species.

**Comment by m-jahn** [comment]
True, but any suggestions where it would be convenient to define?
Preparation of the ref genome is currently an extra step separate from the pipeline. One could call the R script with an additional parameter via command line, or define parameters in the header of the Rmd file.

**Comment by julienmortier** [comment]
Being aware of this is maybe actually the most important part. Changing the reference in the R-script is very straightforward once you're aware of that it needs to happen, so just drawing attention to this fact in the documentation would be enough.

**Comment by m-jahn** [comment]
good idea, and easy to do. I sent you a longer email with some suggestions how to continue with the different issues.
